@startuml
LibraryClient -> Library : findEntityByName(name : String)
loop all entities in list
    Library -> LibraryEntityList : getEntity
    LibraryEntityList -> Library : anEntity
    alt anEntity.name == name
        Library -> ResultEntityList : anEntity
    end
end
ResultEntityList -> LibraryClient : resultList

LibraryClient -> Library : deleteEntity(id : long)
loop all elements in list
    Library -> LibraryEntityList : getEntity
    LibraryEntityList -> Library : anEntity
    alt anEntity.id == id
        Library -> LibraryEntityList : deleteFromList(entity : LibraryEntity)
        Library -> LibraryClient : true
    end
end
Library -> LibraryClient : false


@enduml